### ISSUE TITLE
Error on compile

### ISSUE THREAD

**Issue by aljgardin** [fredvs/uidesigner_ext#5]
Hi Fred.

Can not compile uidesigner_ext.

with newest fpgui download. Develop branch.
Lazarus 2.0 fpc 3.0.4
Windows 7 pro 64 bit.

Get error: fpg_main.pas(186,45) Error: Unknown class field or method
identifier "FWindow"

    property    Window: TfpgWindowBase read FWindow;

Also do you have a patch for Lazarus 2.0 and FPC 3.0.4

**Comment by aljgardin** [comment]
I changed the define.  still will not compile.

**Comment by fredvs** [comment]
Hello.
Did you read my post on fpGui mailing-list? 
Here the resume:

If you want to use last fpgui-develop branch, edit => define.inc
and uncomment {$DEFINE fpgui-develop}.

If you want to use dynamic loading of Xorg and Xft, edit => define.inc
and uncomment ` {$DEFINE DYNLOAD}`.
Depends of the fpGUI branch you are using, copy + paste all files 
in ` /designer_ext/src/xxx_dynx11` into `/designer_ext/src/.`

Here `uidesgner_ext` Linux 64 bit compiled with fpgui-develop branch and fpc 3.0.4:
[designer_ext.zip](https://github.com/fredvs/uidesigner_ext/files/3000431/designer_ext.zip)

![designer_ext_develop](https://user-images.githubusercontent.com/3421249/54880301-9caefd80-4e43-11e9-88d0-bdeb179a8ca1.png)

About Lazarus patch, sorry but I did stop to do patch for new Lazarus version.

**Comment by fredvs** [comment]
Ha you have Windows..

OK, I will check this now.

**Comment by aljgardin** [comment]
I Downloaded Lazarus 1.4.4 and tried the patch with the compiled Program at https://github.com/fredvs/uidesigner_ext/releases/download/1.9/designer_ext_windows32.zip.
This works ok.
with 1.4.4, Tried to compile uidesigner, got the same error with the define set. 
With Lazarus 2.0.0 and FPC 3.0.4  Using the precompiled uidesigner_ext.exe I added an external tool uidesigner_ext with Paramater $EdFile()  This works fine for me. 
Albert J Gardin
(440) 212-2191 

    On Sunday, March 24, 2019 9:57 AM, Fred van Stappen <notifications@github.com> wrote:
 

 Ha you have Windows..OK, I will check this now.—

**Comment by fredvs** [comment]
OK, here compiled version for Windows 32 and 64 bit  (it was out-of-the-box) :

[designer_ext.exe_win32.zip](https://github.com/fredvs/uidesigner_ext/files/3000450/designer_ext.exe_win32.zip)

[designer_ext.exe_win64.zip](https://github.com/fredvs/uidesigner_ext/files/3000453/designer_ext.exe_win64.zip)

Here the result:

![designer_ext_win32_win64](https://user-images.githubusercontent.com/3421249/54880654-4cd23580-4e47-11e9-8e2a-8f00ab799a04.png)

**Comment by fredvs** [comment]
Huh, I do not use Lazarus, so I cannot help a lot.

I did it with ideU: https://github.com/fredvs/ideU/releases

**Comment by aljgardin** [comment]
Thanks.
I can use external tools in Lazarus 2.0.0 for now.
Patch would be nice but not needed.
Thanks again. Albert J Gardin
(440) 212-2191 

    On Sunday, March 24, 2019 10:13 AM, Fred van Stappen <notifications@github.com> wrote:
 

 OK, here compiled version for Windows 32 and 64 bit (it was out-of-the-box) :designer_ext.exe_win32.zipdesigner_ext.exe_win64.zipHere the result:—

**Comment by fredvs** [comment]
OK, I will release the last release asap (but you may use the compiled version from the zip of previous post.

About the patch for Lazarus, I will try to find some energy and time to do it.
(But I need lot of energy because Lazarus code is ***).

Fre;D

**Comment by aljgardin** [comment]
I am good without the patch.I am going to look  at ideU.
Thanks again. Albert J Gardin
(440) 212-2191 

    On Sunday, March 24, 2019 10:21 AM, Fred van Stappen <notifications@github.com> wrote:
 

 OK, I will release the last release asap (but you may use the compiled version from the zip of previous post.About the patch for Lazarus, I will try to find some energy and time to do it.
(But I need lot of energy because Lazarus code is ***).Fre;D—

**Comment by fredvs** [comment]
Here the complete command lne I use for Windows (via Linux wine):

`ppc386.exe -o/home/fred/designer_ext/src/designer_ext.exe -Fu/home/fred/fpGUI-develop/lib/x86_64-Linux -Fi/home/fred/fpGUI-develop/lib/x86_64-Linux -Fu/home/fred/fpGUI-develop -Fi/home/fred/fpGUI-develop -Fu/home/fred/fpGUI-develop/src/corelib/gdi -Fi/home/fred/fpGUI-develop/src/corelib/gdi -Fu/home/fred/fpGUI-develop/src -Fi/home/fred/fpGUI-develop/src -Fu/home/fred/fpGUI-develop/src/gui -Fi/home/fred/fpGUI-develop/src/gui -Fu/home/fred/fpGUI-develop/src/corelib -Fi/home/fred/fpGUI-develop/src/corelib -Fu./maint_x11 -Fi./maint_x11 -Fl./maint_x11 -Fo./maint_x11 -Fu./dynX11 -Fi./dynX11 -Fl./dynX11 -Fo./dynX11 -l -Mobjfpc -Schi -FE. -FUunits -B -O1 -XX -Xs -CX -WG -vewnhibqw /home/fred/designer_ext/src/designer_ext.pas`

**Comment by fredvs** [comment]
> I am going to look  at ideU.

Ha, if you use ideU, designer_ext is included and integrated into ideU.

**Comment by fredvs** [comment]
Note that if you use deU and load designer_ext.prj you will need to check  the Project-option.

I use ideU as multi-OS compiler so there are some project-options number that are for Linux and others for Windows.

Use the Project option number assigned for Windows.

**Comment by fredvs** [comment]
Ooops, edited https://github.com/fredvs/uidesigner_ext/issues/5#issuecomment-475964332

It was not the right command line, the edited s the good one.
